{
    "openapi":"3.0.2",
    "info": {
        "title":"Restorant API",
        "version":"1.1"
    },
    "servers": [
        {
            "url":"http://localhost:8000"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth":{
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "bearer"
            }
        },
        "responses": {
            "UnauthorizedError":{
                "description": "Access token hilang atau tidak valid, masukan token dari hasil login",
                "content": {
                    "application/json":{
                        "example": {
                            "massage": "Unauthenticated"
                        }
                    }
                }
            },
            "data not found":{
                "description": "data tidak ditemukan",
                "content": {
                    "application/json":{
                        "example": {
                            "massage": "data not found"
                        }
                    }
                }
            }
        }
    },
    "paths": {
        "/api/user/restorant/create":{
            "post":{
                "description": "Membuat restorant baru berdasarkan user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "address", "latlong", "photo"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "address" :{
                                        "type": "string"
                                    },
                                    "latlong" :{
                                        "type": "string"
                                    },
                                    "photo":{
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create new restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    },
                                    "errors":{}
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        },
                                        "errors" : {
                                            "type": "object"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "example": {
                                    "massage" : "massage error",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "address" : [
                                            "address tidak boleh kosong"
                                        ],
                                        "latlong" : [
                                            "latlong tidak boleh kosong",
                                            "latlong tidak valid"
                                        ],
                                        "photo": [
                                            "photo tidak boleh kosong",
                                            "photo maksimal berukuran 10mb"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant":{
            "get":{
                "description": "mengambil restorant berdasrkan kepunyaan user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "201":{
                        "description": "success get current restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    },
                                    "errors":{}
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        },
                                        "errors" : {
                                            "type": "object"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "Unauthenticated",
                        "content": {
                            "application/json" : {
                                "example": {
                                    "massage" : "Unauthenticated"
                                }
                            }
                        }
                    }
                }
            },
            "patch":{
                "description": "update data restorant berdasarkan kepunyaannya user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "address" :{
                                        "type": "string"
                                    },
                                    "latlong" :{
                                        "type": "string"
                                    },
                                    "photo":{
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create new restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    },
                                    "errors":{}
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        },
                                        "errors" : {
                                            "type": "object"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "example": {
                                    "massage" : "massage error",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "address" : [
                                            "address tidak boleh kosong"
                                        ],
                                        "latlong" : [
                                            "latlong tidak boleh kosong",
                                            "latlong tidak valid"
                                        ],
                                        "photo": [
                                            "photo tidak boleh kosong",
                                            "photo maksimal berukuran 10mb"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant/products":{
            "get":{
                "summary": "mengambil semua product menu yang ada pada restorant",
                "description": "mengambil menu yang tersedia berdasarkan kepunyaannya user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get all products",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data": [
                                        {
                                            "id": 2,
                                            "name": "nasi goreng padang",
                                            "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                            "deskripsi": "nasi goreng bumbu padaang asli",
                                            "type": "makanan",
                                            "harga": 12000,
                                            "stock": "ada"
                                        },
                                        {
                                            "id": 3,
                                            "name": "nasi kabuli arab",
                                            "image": "http://localhost:8080/api/restorant/photo/sdgj566efsdffgddfg.jpg",
                                            "deskripsi": "nasi yang dibuli asli",
                                            "type": "makanan",
                                            "harga": 15000,
                                            "stock": "habis"
                                        },
                                        {
                                            "id": 5,
                                            "name": "es teh anget",
                                            "image": "http://localhost:8080/api/restorant/photo/fsdfsdrrfgh4663dfd.jpg",
                                            "deskripsi": "es teh anget",
                                            "type": "minuman",
                                            "harga": 3000,
                                            "stock": "ada"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "description": "jika data product tidak ada terdaftar",
                        "content": {
                            "application/json":{
                                "example": {
                                    "errors":{
                                        "massage": "tidak ada product terdaftar"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant/product/create":{
            "post":{
                "description": "menambah menu restorant berdasarkan kepunyaannya user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "image", "deskripsi", "type", "harga"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "image":{
                                        "type": "string",
                                        "format": "binary"
                                    },
                                    "deskripsi" :{
                                        "type": "string"
                                    },
                                    "type" :{
                                        "type": "string",
                                        "enum": ["makanan", "minuman"]
                                    },
                                    "harga": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create product",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data":{
                                        "id": 2,
                                        "name": "nasi goreng padang",
                                        "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "deskripsi": "nasi goreng bumbu padaang asli",
                                        "type": "makanan",
                                        "harga": 12000,
                                        "stock": "ada",
                                        "created_at": "datetime",
                                        "updated_at": "datetime"
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "image":{"type": "string"},
                                                "deskripsi":{"type": "string"},
                                                "type":{"type": "string"},
                                                "harga":{"type": "number"},
                                                "stock":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "validation Error",
                        "content": {
                            "application/json":{
                                "example": {
                                    "massage": "massage validasi errors",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "image" : [
                                            "image tidak boleh kosong",
                                            "image tidak boleh lebih dari 10mb"
                                        ],
                                        "deskripsi" : [
                                            "deskripsi tidak boleh kosong"
                                        ],
                                        "type": [
                                            "type tidak boleh kosong",
                                            "type harus antara makanan dan minuman"
                                        ],
                                        "harga":[
                                            "harga tidak boleh kosong",
                                            "harga tidak boleh mengandung huruf"
                                        ]
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "massage" :{"type": "string"},
                                        "errors":{"type": "object"}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant/product/{id}":{
            "get":{
                "summary": "mengambil product spesifik berdasarkan id",
                "description": "menampilkan product berdasarkan id yang diberikan",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema":{
                            "type": "integer",
                            "minimum": 1
                        }
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success create product",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "endpoint/product/2":{
                                        "value":{
                                            "data":{
                                                "id": 2,
                                                "name": "nasi goreng padang",
                                                "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                                "deskripsi": "nasi goreng bumbu padaang asli",
                                                "type": "makanan",
                                                "harga": 12000,
                                                "stock": "ada",
                                                "created_at": "datetime",
                                                "updated_at": "datetime"
                                            }
                                        }
                                    },
                                    "endpoint/product/3":{
                                        "value":{
                                            "data":{
                                                "id": 3,
                                                "name": "nasi kabuli arab",
                                                "image": "http://localhost:8080/api/restorant/photo/sdgj566efsdffgddfg.jpg",
                                                "deskripsi": "nasi yang dibuli asli",
                                                "type": "makanan",
                                                "harga": 15000,
                                                "stock": "habis",
                                                "created_at": "datetime",
                                                "updated_at": "datetime"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "description": "product tidak ditemukan",
                        "content": {
                            "application/json":{
                                "example": {
                                    "errors":{
                                        "massage": "product tidak ditemukan"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch":{
                "description": "mengedit data product berdasarkan id yang diberikan",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "image", "deskripsi", "type", "harga"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "image":{
                                        "type": "string",
                                        "format": "binary"
                                    },
                                    "deskripsi" :{
                                        "type": "string"
                                    },
                                    "type" :{
                                        "type": "string",
                                        "enum": ["makanan", "minuman"]
                                    },
                                    "harga": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "product berhasil diubah",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data":{
                                        "id": 2,
                                        "name": "nasi goreng padang",
                                        "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "deskripsi": "nasi goreng bumbu padaang asli",
                                        "type": "makanan",
                                        "harga": 12000,
                                        "stock": "ada",
                                        "created_at": "datetime",
                                        "updated_at": "datetime"
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "description": "product tidak ditemukan",
                        "content": {
                            "application/json":{
                                "example": {
                                    "errors":{
                                        "massage": "product tidak ditemukan"
                                    }
                                }
                            }
                        }
                    },
                    "422":{
                        "description": "validation Error",
                        "content": {
                            "application/json":{
                                "example": {
                                    "massage": "massage validasi errors",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "image" : [
                                            "image tidak boleh kosong",
                                            "image tidak boleh lebih dari 10mb"
                                        ],
                                        "deskripsi" : [
                                            "deskripsi tidak boleh kosong"
                                        ],
                                        "type": [
                                            "type tidak boleh kosong",
                                            "type harus antara makanan dan minuman"
                                        ],
                                        "harga":[
                                            "harga tidak boleh kosong",
                                            "harga tidak boleh mengandung huruf"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "description": "menghapus data product berdasarkan id yang diberikan",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "204":{
                        "description": "success hapus produk, **tidak ada informasi balik response**",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "endpoint/product/2":{

                                    },
                                    "endpoint/product/3":{
                                        
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "description": "product tidak ditemukan",
                        "content": {
                            "application/json":{
                                "example": {
                                    "errors":{
                                        "massage": "product tidak ditemukan"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant/orders":{
            "get":{
                "summary": "riwayat order",
                "description": "mengambil order yang tersedia untuk saat ini, berdasarkan restorant kepunyaannya user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ]
            }
        },

        "/api/restorants":{
            "get":{
                "summary": "mengambil semua data restorant",
                "tags": ["global"],
                "parameters": [
                    {
                        "in": "query",
                        "name": "search",
                        "schema":{
                            "type": "string"
                        },
                        "description": "kata kunci"
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success mengambil data restorant yang ada",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "ada data":{
                                        "value":
                                        [
                                            {
                                                "current_page": 1,
                                                "data": [
                                                  {
                                                    "id": 42,
                                                    "user_id": 63,
                                                    "name": "Bernhard-Cummings",
                                                    "address": "43185 Lorna Prairie Suite 040\nEast Myrl, NY 25930",
                                                    "latlong": "-71.271151,-114.158795",
                                                    "photo": null,
                                                    "created_at": "2024-06-25T16:01:23.000000Z",
                                                    "updated_at": "2024-06-25T16:01:23.000000Z",
                                                    "products": [
                                                      {
                                                        "id": 52,
                                                        "restorant_id": 42,
                                                        "name": "Raleigh Willms",
                                                        "image": "https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg",
                                                        "deskripsi": "Voluptatem numquam veniam deleniti vel dolores quaerat doloribus. Ut veniam modi sunt officia atque sit.",
                                                        "type": "minuman",
                                                        "harga": 9705,
                                                        "created_at": "2024-06-25T16:01:23.000000Z",
                                                        "updated_at": "2024-06-25T16:01:23.000000Z"
                                                      },
                                                      {
                                                        "id": 53,
                                                        "restorant_id": 42,
                                                        "name": "Mertie Vandervort",
                                                        "image": "https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg",
                                                        "deskripsi": "Totam voluptatem dolorum accusamus nulla earum.",
                                                        "type": "makanan",
                                                        "harga": 8541,
                                                        "created_at": "2024-06-25T16:01:23.000000Z",
                                                        "updated_at": "2024-06-25T16:01:23.000000Z"
                                                      }
                                                    ]
                                                  }
                                                  
                                                ],
                                                "first_page_url": "http://127.0.0.1:8000/api/restorants?page=1",
                                                "from": 1,
                                                "last_page": 2,
                                                "last_page_url": "http://127.0.0.1:8000/api/restorants?page=2",
                                                "links": [
                                                {
                                                    "url": null,
                                                    "label": "&laquo; Previous",
                                                    "active": false
                                                },
                                                {
                                                    "url": "http://127.0.0.1:8000/api/restorants?page=1",
                                                    "label": "1",
                                                    "active": true
                                                },
                                                {
                                                    "url": "http://127.0.0.1:8000/api/restorants?page=2",
                                                    "label": "2",
                                                    "active": false
                                                },
                                                {
                                                    "url": "http://127.0.0.1:8000/api/restorants?page=2",
                                                    "label": "Next &raquo;",
                                                    "active": false
                                                }
                                                ],
                                                "next_page_url": "http://127.0.0.1:8000/api/restorants?page=2",
                                                "path": "http://127.0.0.1:8000/api/restorants",
                                                "per_page": 10,
                                                "prev_page_url": null,
                                                "to": 2,
                                                "total": 2
                                            }
                                        ]
                                    },
                                    "tidak ada data":{
                                        "value":
                                        [
                                            {
                                                "current_page": 1,
                                                "data": [],
                                                "first_page_url": "http://127.0.0.1:8000/api/restorants?page=1",
                                                "from": null,
                                                "last_page": 1,
                                                "last_page_url": "http://127.0.0.1:8000/api/restorants?page=1",
                                                "links": [
                                                {
                                                    "url": null,
                                                    "label": "&laquo; Previous",
                                                    "active": false
                                                },
                                                {
                                                    "url": "http://127.0.0.1:8000/api/restorants?page=1",
                                                    "label": "1",
                                                    "active": true
                                                },
                                                {
                                                    "url": null,
                                                    "label": "Next &raquo;",
                                                    "active": false
                                                }
                                                ],
                                                "next_page_url": null,
                                                "path": "http://127.0.0.1:8000/api/restorants",
                                                "per_page": 10,
                                                "prev_page_url": null,
                                                "to": null,
                                                "total": 0
                                              }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/restorant/{id}":{
            "get":{
                "description": "mengambil data restorant yang ditargetkan",
                "tags": ["global"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema":{
                            "type": "integer",
                            "minimum": 1
                        }
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get restorant data",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "user_id": 1,
                                        "name": "Rolfson-Stehr",
                                        "address": "106 Kay Burgs Apt. 035\nTristianfurt, OR 36584",
                                        "latlong": "-34.584442,-71.856743",
                                        "photo": null,
                                        "created_at": "2024-06-25T16:14:32.000000Z",
                                        "updated_at": "2024-06-25T16:14:32.000000Z",
                                        "products": [
                                        {
                                            "id": 1,
                                            "restorant_id": 1,
                                            "name": "Tina Roob",
                                            "image": "https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg",
                                            "deskripsi": "Non aut rerum et dicta corrupti.",
                                            "type": "makanan",
                                            "harga": 6618,
                                            "created_at": "2024-06-25T16:14:32.000000Z",
                                            "updated_at": "2024-06-25T16:14:32.000000Z"
                                        },
                                        {
                                            "id": 2,
                                            "restorant_id": 1,
                                            "name": "Mason Stoltenberg",
                                            "image": "https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg",
                                            "deskripsi": "Temporibus odio a sapiente.",
                                            "type": "makanan",
                                            "harga": 3182,
                                            "created_at": "2024-06-25T16:14:32.000000Z",
                                            "updated_at": "2024-06-25T16:14:32.000000Z"
                                        }]
                                    }
                                }
                            }
                        }
                    },

                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }
            }
        },
        "/api/restorant/{id}/product/{product_id}":{
            "get":{
                "description": "mendapatkan product restorant spesifik",
                "tags": ["global"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema":{
                            "type": "integer",
                            "minimum": 1
                        }
                    },
                    {
                        "in": "path",
                        "name": "product_id",
                        "required": true,
                        "schema":{
                            "type": "integer",
                            "minimum": 1
                        }
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get product restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data": {
                                        "id": 2,
                                        "restorant_id": 1,
                                        "name": "Mason Stoltenberg",
                                        "image": "https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg",
                                        "deskripsi": "Temporibus odio a sapiente.",
                                        "type": "makanan",
                                        "harga": 3182,
                                        "created_at": "2024-06-25T16:14:32.000000Z",
                                        "updated_at": "2024-06-25T16:14:32.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }
            }
        }
    }
  }