{
    "openapi":"3.0.2",
    "info": {
        "title":"User API",
        "version":"1.0.2"
    },
    "servers": [
        {
            "url":"http://localhost:8000"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth":{
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "bearer"
            }
        },
        "responses": {
            "UnauthorizedError":{
                "description": "Access token hilang atau tidak valid, masukan token dari hasil login",
                "content": {
                    "application/json":{
                        "examples": {
                            "Unauthorized Massage":{
                                "value":{
                                    "massage": "Unauthenticated"
                                }
                            }
                        }
                    }
                }
            },
            "data not found":{
                "description": "data tidak ditemukan",
                "content": {
                    "application/json":{
                        "example": {
                            "massage": "data not found"
                        }
                    }
                }
            }
        }
    },
    "paths": {
        "/api/user/register" :{
            "post":{
                "description": "Register new user",
                "tags": ["Auth User"],
                "requestBody":{
                    "content": {
                        "application/json" :{
                            "examples": {
                                "standart" :{
                                    "description": "Register untuk standart user",
                                    "value": {
                                        "name" : "daffa alif",
                                        "email" : "daffa@saja.com",
                                        "phone" : 829273723,
                                        "password" : "rahasia"
                                    }
                                }
                            },
                            "schema" :{
                                "type": "object",
                                "required": ["name", "email", "phone", "password"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "email" :{
                                        "type": "string"
                                    },
                                    "phone" :{
                                        "type": "number"
                                    },
                                    "password":{
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success register new user",
                        "content": {
                            "application/json" : {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "email":{"type": "string"},
                                                "phone":{"type": "number"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "examples": {
                                    "validationError":{
                                        "description": "contoh validasi error",
                                        "value": {
                                            "massage" : "massage error",
                                            "errors": {
                                                "name": [
                                                    "name tidak boleh kosong",
                                                    "name tidak boleh mengandung angka"
                                                ],
                                                "email" : [
                                                    "email tidak boleh kosong",
                                                    "email tidak valid"
                                                ],
                                                "phone" : [
                                                    "phone tidak boleh kosong",
                                                    "phone tidak valid"
                                                ],
                                                "password": [
                                                    "password tidak boleh kosong",
                                                    "password harus lebih dari 6 karakter"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/login" :{
            "post":{
                "description": "Login exists user",
                "tags": ["Auth User"],
                "requestBody":{
                    "content": {
                        "application/json" :{
                            "examples": {
                                "standart email" :{
                                    "description": "Login untuk standart user menggunakan email",
                                    "value": {
                                        "credential" : "daffa@saja.com",
                                        "password" : "rahasia"
                                    }
                                },
                                "standart phone" :{
                                    "description": "Login untuk standart user menggunakan phone",
                                    "value": {
                                        "credential" : "088662352",
                                        "password" : "rahasia"
                                    }
                                }
                            },
                            "schema" :{
                                "type": "object",
                                "required": ["credential", "password"],
                                "properties": {
                                    "credential":{
                                        "type": "string"
                                    },
                                    "password":{
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "success login user",
                        "content": {
                            "application/json" : {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "email":{"type": "string"},
                                                "phone":{"type": "number"},
                                                "token":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "Unauthorized, gagal login",
                        "content": {
                            "application/json" : {
                                "examples": {
                                    "Unauthorized Email":{
                                        "description": "contoh gagal login menggunakan email",
                                        "value": {
                                            "errors": {
                                                "massage" : "password dan email yang dimasukan salah"
                                            }
                                        }
                                    },
                                    "Unauthorized Phone":{
                                        "description": "contoh gagal login menggunakan phone",
                                        "value": {
                                            "errors": {
                                                "massage" : "password dan phone yang dimasukan salah"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "examples": {
                                    "Validation error":{
                                        "description": "contoh validasi error",
                                        "value": {
                                            "errors": {
                                                "credential": [
                                                    "credential tidak boleh kosong"
                                                ],
                                                "password": [
                                                    "password tidak boleh kosong"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user" :{
            "get":{
                "description": "get current user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get current user",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "email":{"type": "string"},
                                                "phone":{"type": "number"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    }
                }
                
            },
            "patch": {
                "description": "Update current user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "description": "update current user",
                    "content": {
                        "application/json" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "email", "phone", "password"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "email" :{
                                        "type": "string"
                                    },
                                    "phone" :{
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "success update current user",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "email":{"type": "string"},
                                                "phone":{"type": "number"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    }
                }
            }
        },
        "/api/user/logout": {
            "delete": {
                "description": "Logout current user",
                "tags": ["Auth User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success logout current user",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    }
                }
            }
        },

        "/api/user/restorant/create":{
            "post":{
                "description": "Membuat restorant baru berdasarkan user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "address", "latlong", "photo"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "address" :{
                                        "type": "string"
                                    },
                                    "latlong" :{
                                        "type": "string"
                                    },
                                    "photo":{
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create new restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "example": {
                                    "massage" : "massage error",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "address" : [
                                            "address tidak boleh kosong"
                                        ],
                                        "latlong" : [
                                            "latlong tidak boleh kosong",
                                            "latlong tidak valid"
                                        ],
                                        "photo": [
                                            "photo tidak boleh kosong",
                                            "photo maksimal berukuran 10mb"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant":{
            "get":{
                "description": "mengambil restorant berdasrkan kepunyaan user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "201":{
                        "description": "success get current restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    },
                                    "errors":{}
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        },
                                        "errors" : {
                                            "type": "object"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    }
                }
            },
            "patch":{
                "description": "update data restorant berdasarkan kepunyaannya user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "address" :{
                                        "type": "string"
                                    },
                                    "latlong" :{
                                        "type": "string"
                                    },
                                    "photo":{
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create new restorant",
                        "content": {
                            "application/json":{
                                "example":{
                                    "data":{
                                        "id": 1,
                                        "name": "Jogja Pret Chiken",
                                        "address": "jln. kaliurang km 10",
                                        "latlong": "-200.234, 10.24546",
                                        "photo": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "created_at": "date format",
                                        "updated_at": "date format"
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "address":{"type": "string"},
                                                "latlong":{"type": "string"},
                                                "photo":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "Validation error",
                        "content": {
                            "application/json" : {
                                "example": {
                                    "massage" : "massage error",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "address" : [
                                            "address tidak boleh kosong"
                                        ],
                                        "latlong" : [
                                            "latlong tidak boleh kosong",
                                            "latlong tidak valid"
                                        ],
                                        "photo": [
                                            "photo tidak boleh kosong",
                                            "photo maksimal berukuran 10mb"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "description": "mengambil restorant berdasrkan kepunyaan user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "204":{
                        "description": "success menghapus restorant user. no response object"
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }                
            }
        },
        "/api/user/restorant/products":{
            "get":{
                "summary": "mengambil semua product menu yang ada pada restorant",
                "description": "mengambil menu yang tersedia berdasarkan kepunyaannya user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get all products",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data": [
                                        {
                                            "id": 2,
                                            "name": "nasi goreng padang",
                                            "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                            "deskripsi": "nasi goreng bumbu padaang asli",
                                            "type": "makanan",
                                            "harga": 12000,
                                            "stock": "ada"
                                        },
                                        {
                                            "id": 3,
                                            "name": "nasi kabuli arab",
                                            "image": "http://localhost:8080/api/restorant/photo/sdgj566efsdffgddfg.jpg",
                                            "deskripsi": "nasi yang dibuli asli",
                                            "type": "makanan",
                                            "harga": 15000,
                                            "stock": "habis"
                                        },
                                        {
                                            "id": 5,
                                            "name": "es teh anget",
                                            "image": "http://localhost:8080/api/restorant/photo/fsdfsdrrfgh4663dfd.jpg",
                                            "deskripsi": "es teh anget",
                                            "type": "minuman",
                                            "harga": 3000,
                                            "stock": "ada"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }
            }
        },
        "/api/user/restorant/product/create":{
            "post":{
                "description": "menambah menu restorant berdasarkan kepunyaannya user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "image", "deskripsi", "type", "harga"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "image":{
                                        "type": "string",
                                        "format": "binary"
                                    },
                                    "deskripsi" :{
                                        "type": "string"
                                    },
                                    "type" :{
                                        "type": "string",
                                        "enum": ["makanan", "minuman"]
                                    },
                                    "harga": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "success create product",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data":{
                                        "id": 2,
                                        "name": "nasi goreng padang",
                                        "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "deskripsi": "nasi goreng bumbu padaang asli",
                                        "type": "makanan",
                                        "harga": 12000,
                                        "stock": "ada",
                                        "created_at": "datetime",
                                        "updated_at": "datetime"
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data" : {
                                            "type": "object",
                                            "properties": {
                                                "id" :{"type": "number"},
                                                "name":{"type": "string"},
                                                "image":{"type": "string"},
                                                "deskripsi":{"type": "string"},
                                                "type":{"type": "string"},
                                                "harga":{"type": "number"},
                                                "stock":{"type": "string"},
                                                "created_at":{"type": "string"},
                                                "updated_at":{"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "422":{
                        "description": "validation Error",
                        "content": {
                            "application/json":{
                                "example": {
                                    "massage": "massage validasi errors",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "image" : [
                                            "image tidak boleh kosong",
                                            "image tidak boleh lebih dari 10mb"
                                        ],
                                        "deskripsi" : [
                                            "deskripsi tidak boleh kosong"
                                        ],
                                        "type": [
                                            "type tidak boleh kosong",
                                            "type harus antara makanan dan minuman"
                                        ],
                                        "harga":[
                                            "harga tidak boleh kosong",
                                            "harga tidak boleh mengandung huruf"
                                        ]
                                    }
                                },
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "massage" :{"type": "string"},
                                        "errors":{"type": "object"}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/restorant/product/{id}":{
            "get":{
                "summary": "mengambil product spesifik berdasarkan id",
                "description": "menampilkan product berdasarkan id yang diberikan",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema":{
                            "type": "integer",
                            "minimum": 1
                        }
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success create product",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "endpoint/product/2":{
                                        "value":{
                                            "data":{
                                                "id": 2,
                                                "name": "nasi goreng padang",
                                                "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                                "deskripsi": "nasi goreng bumbu padaang asli",
                                                "type": "makanan",
                                                "harga": 12000,
                                                "stock": "ada",
                                                "created_at": "datetime",
                                                "updated_at": "datetime"
                                            }
                                        }
                                    },
                                    "endpoint/product/3":{
                                        "value":{
                                            "data":{
                                                "id": 3,
                                                "name": "nasi kabuli arab",
                                                "image": "http://localhost:8080/api/restorant/photo/sdgj566efsdffgddfg.jpg",
                                                "deskripsi": "nasi yang dibuli asli",
                                                "type": "makanan",
                                                "harga": 15000,
                                                "stock": "habis",
                                                "created_at": "datetime",
                                                "updated_at": "datetime"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }
            },
            "patch":{
                "description": "mengedit data product berdasarkan id yang diberikan",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "requestBody":{
                    "content": {
                        "multipart/form-data" :{
                            "schema":{
                                "type": "object",
                                "required": ["name", "image", "deskripsi", "type", "harga"],
                                "properties": {
                                    "name":{
                                        "type": "string"
                                    },
                                    "image":{
                                        "type": "string",
                                        "format": "binary"
                                    },
                                    "deskripsi" :{
                                        "type": "string"
                                    },
                                    "type" :{
                                        "type": "string",
                                        "enum": ["makanan", "minuman"]
                                    },
                                    "harga": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "product berhasil diubah",
                        "content": {
                            "application/json":{
                                "example": {
                                    "data":{
                                        "id": 2,
                                        "name": "nasi goreng padang",
                                        "image": "http://localhost:8080/api/restorant/photo/sd834bjsdasdeotmdojjf.jpg",
                                        "deskripsi": "nasi goreng bumbu padaang asli",
                                        "type": "makanan",
                                        "harga": 12000,
                                        "stock": "ada",
                                        "created_at": "datetime",
                                        "updated_at": "datetime"
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    },
                    "422":{
                        "description": "validation Error",
                        "content": {
                            "application/json":{
                                "example": {
                                    "massage": "massage validasi errors",
                                    "errors": {
                                        "name": [
                                            "name tidak boleh kosong"
                                        ],
                                        "image" : [
                                            "image tidak boleh kosong",
                                            "image tidak boleh lebih dari 10mb"
                                        ],
                                        "deskripsi" : [
                                            "deskripsi tidak boleh kosong"
                                        ],
                                        "type": [
                                            "type tidak boleh kosong",
                                            "type harus antara makanan dan minuman"
                                        ],
                                        "harga":[
                                            "harga tidak boleh kosong",
                                            "harga tidak boleh mengandung huruf"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "description": "menghapus data product berdasarkan id yang diberikan",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "204":{
                        "description": "success hapus produk, **tidak ada informasi balik response**",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "endpoint/product/2":{

                                    },
                                    "endpoint/product/3":{
                                        
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "$ref": "#/components/responses/UnauthorizedError"
                    },
                    "404":{
                        "$ref": "#/components/responses/data not found"
                    }
                }
            }
        },
        "/api/user/restorant/orders":{
            "get":{
                "summary": "riwayat order",
                "description": "mengambil order yang tersedia untuk saat ini, berdasarkan restorant kepunyaannya user",
                "tags": ["Restorant User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ]
            }
        },

        "/api/user/orders":{
            "get":{
                "summary": "get user order in 1 month",
                "description": "mengambil data user orders selama 1 bulan ini, secara terbaru, dan sesuai urutan staus: delivery, done/cancel",
                "tags": ["Order User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get orders data 1 bulan lalu",
                        "content": {
                            "application/json":{
                                "examples": {
                                    "jika ada data":{
                                        "value":{
                                            "data":[
                                                
                                            ]
                                        }
                                    },
                                    "tidak ada data":{

                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/order":{
            "post":{
                "tags": ["Order User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "201":{
                        "description": "success create order data"
                    }
                }
            }
        },
        "/api/user/order/{id}":{
            "get":{
                "tags": ["Order User"],
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success get order data"
                    }
                }
            }
        }
    }
}